package com.example.helpmeow

class Object {
    companion object {
        val role = arrayOf("Seeker", "Gifter")
        val gender = arrayOf("Male", "Female")
        val breed = arrayOf("Burmilla",
                "Cymric",
                "LaPerm",
                "American Wirehair",
                "Singapura",
                "Chausie",
                "Somali",
                "Oriental Long Hair",
                "Korat",
                "Selkirk Rex",
                "Chartreux",
                "Pixiebob",
                "Ocicat",
                "Devon Rex",
                "Japanese Bobtail",
                "Ragamuffin",
                "Nebelung",
                "American Curl",
                "Cornish Rex",
                "Munchkin",
                "Havana",
                "Siberian",
                "Sphynx",
                "Birman",
                "Balinese",
                "Abyssinian",
                "Tonkinese",
                "Egyptian Mau",
                "Burmese",
                "Scottish Fold",
                "Exotic Shorthair",
                "Oriental Short Hair",
                "British Shorthair",
                "Norwegian Forest Cat",
                "Turkish Angora",
                "Turkish Van",
                "American Bobtail",
                "Himalayan",
                "Maine Coon",
                "Snowshoe",
                "Bombay",
                "Russian Blue",
                "Manx",
                "Bengal",
                "Ragdoll",
                "Siamese",
                "Persian",
                "Domestic Long Hair",
                "American Shorthair",
                "Domestic Medium Hair")
    }
}